interface Ta4jCompletion {
  label: string
  detail: string
  insertText: string
  type: 'class' | 'method' | 'import'
}

const TA4J_IMPORTS: Ta4jCompletion[] = [
  { label: 'import org.ta4j.core.*', detail: '导入 ta4j 核心包', insertText: "import org.ta4j.core.*;", type: 'import' },
  { label: 'import org.ta4j.core.BarSeries', detail: 'K线序列接口', insertText: "import org.ta4j.core.BarSeries;", type: 'import' },
  { label: 'import org.ta4j.core.BaseBarSeriesBuilder', detail: 'K线序列构建器', insertText: "import org.ta4j.core.BaseBarSeriesBuilder;", type: 'import' },
  { label: 'import org.ta4j.core.Indicator', detail: '指标接口', insertText: "import org.ta4j.core.Indicator;", type: 'import' },
  { label: 'import org.ta4j.core.Rule', detail: '规则接口', insertText: "import org.ta4j.core.Rule;", type: 'import' },
  { label: 'import org.ta4j.core.Strategy', detail: '策略接口', insertText: "import org.ta4j.core.Strategy;", type: 'import' },
  { label: 'import org.ta4j.core.BaseStrategy', detail: '策略实现类', insertText: "import org.ta4j.core.BaseStrategy;", type: 'import' },
  { label: 'import org.ta4j.core.TradingRecord', detail: '交易记录', insertText: "import org.ta4j.core.TradingRecord;", type: 'import' },
  { label: 'import org.ta4j.core.Trade', detail: '单笔交易', insertText: "import org.ta4j.core.Trade;", type: 'import' },
  { label: 'import org.ta4j.core.Position', detail: '持仓', insertText: "import org.ta4j.core.Position;", type: 'import' },
  { label: 'import org.ta4j.core.backtest.BarSeriesManager', detail: '序列管理器', insertText: "import org.ta4j.core.backtest.BarSeriesManager;", type: 'import' },
  { label: 'import org.ta4j.core.num.Num', detail: '数值类型', insertText: "import org.ta4j.core.num.Num;", type: 'import' },
  { label: 'import org.ta4j.core.num.DecimalNumFactory', detail: '高精度数值工厂', insertText: "import org.ta4j.core.num.DecimalNumFactory;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.averages.*', detail: '导入均线指标', insertText: "import org.ta4j.core.indicators.averages.*;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.averages.SMAIndicator', detail: '简单移动平均线', insertText: "import org.ta4j.core.indicators.averages.SMAIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.averages.EMAIndicator', detail: '指数移动平均线', insertText: "import org.ta4j.core.indicators.averages.EMAIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.averages.WMAIndicator', detail: '加权移动平均线', insertText: "import org.ta4j.core.indicators.averages.WMAIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.averages.LWMAIndicator', detail: '线性加权移动平均线', insertText: "import org.ta4j.core.indicators.averages.LWMAIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.RSIIndicator', detail: 'RSI指标', insertText: "import org.ta4j.core.indicators.RSIIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.MACDIndicator', detail: 'MACD指标', insertText: "import org.ta4j.core.indicators.MACDIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ROCIndicator', detail: '变动率指标', insertText: "import org.ta4j.core.indicators.ROCIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.PPOIndicator', detail: '价格震荡百分比', insertText: "import org.ta4j.core.indicators.PPOIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.CCIIndicator', detail: '商品通道指标', insertText: "import org.ta4j.core.indicators.CCIIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ATRIndicator', detail: '真实波幅均值', insertText: "import org.ta4j.core.indicators.ATRIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.WilliamsRIndicator', detail: '威廉指标', insertText: "import org.ta4j.core.indicators.WilliamsRIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.DPOIndicator', detail: '去趋势价格指标', insertText: "import org.ta4j.core.indicators.DPOIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ChopIndicator', detail: 'Choppiness指数', insertText: "import org.ta4j.core.indicators.ChopIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.StochasticOscillatorKIndicator', detail: 'KDJ之K值', insertText: "import org.ta4j.core.indicators.StochasticOscillatorKIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.StochasticOscillatorDIndicator', detail: 'KDJ之D值', insertText: "import org.ta4j.core.indicators.StochasticOscillatorDIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ParabolicSarIndicator', detail: '抛物线SAR指标', insertText: "import org.ta4j.core.indicators.ParabolicSarIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ichimoku.*', detail: '导入一目均衡表指标', insertText: "import org.ta4j.core.indicators.ichimoku.*;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ichimoku.IchimokuTenkanSenIndicator', detail: '一目转换线', insertText: "import org.ta4j.core.indicators.ichimoku.IchimokuTenkanSenIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ichimoku.IchimokuKijunSenIndicator', detail: '一目基准线', insertText: "import org.ta4j.core.indicators.ichimoku.IchimokuKijunSenIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ichimoku.IchimokuSenkouSpanAIndicator', detail: '一目先行带A', insertText: "import org.ta4j.core.indicators.ichimoku.IchimokuSenkouSpanAIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ichimoku.IchimokuSenkouSpanBIndicator', detail: '一目先行带B', insertText: "import org.ta4j.core.indicators.ichimoku.IchimokuSenkouSpanBIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.ichimoku.IchimokuChikouSpanIndicator', detail: '一目延迟线', insertText: "import org.ta4j.core.indicators.ichimoku.IchimokuChikouSpanIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.candles.*', detail: '导入所有K线形态指标', insertText: "import org.ta4j.core.indicators.candles.*;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.candles.BullishEngulfingIndicator', detail: '看涨吞没形态', insertText: "import org.ta4j.core.indicators.candles.BullishEngulfingIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.candles.BearishEngulfingIndicator', detail: '看跌吞没形态', insertText: "import org.ta4j.core.indicators.candles.BearishEngulfingIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.candles.HammerIndicator', detail: '锤子线形态', insertText: "import org.ta4j.core.indicators.candles.HammerIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.candles.DojiIndicator', detail: '十字星形态', insertText: "import org.ta4j.core.indicators.candles.DojiIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.candles.MorningStarIndicator', detail: '晨星形态', insertText: "import org.ta4j.core.indicators.candles.MorningStarIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.candles.EveningStarIndicator', detail: '暮星形态', insertText: "import org.ta4j.core.indicators.candles.EveningStarIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.bollinger.*', detail: '导入布林带指标', insertText: "import org.ta4j.core.indicators.bollinger.*;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.bollinger.BollingerBandsLowerIndicator', detail: '布林带下轨', insertText: "import org.ta4j.core.indicators.bollinger.BollingerBandsLowerIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.bollinger.BollingerBandsMiddleIndicator', detail: '布林带中轨', insertText: "import org.ta4j.core.indicators.bollinger.BollingerBandsMiddleIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.bollinger.BollingerBandsUpperIndicator', detail: '布林带上轨', insertText: "import org.ta4j.core.indicators.bollinger.BollingerBandsUpperIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.*', detail: '导入辅助指标', insertText: "import org.ta4j.core.indicators.helpers.*;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.ClosePriceIndicator', detail: '收盘价指标', insertText: "import org.ta4j.core.indicators.helpers.ClosePriceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.OpenPriceIndicator', detail: '开盘价指标', insertText: "import org.ta4j.core.indicators.helpers.OpenPriceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.HighPriceIndicator', detail: '最高价指标', insertText: "import org.ta4j.core.indicators.helpers.HighPriceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.LowPriceIndicator', detail: '最低价指标', insertText: "import org.ta4j.core.indicators.helpers.LowPriceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.VolumeIndicator', detail: '成交量指标', insertText: "import org.ta4j.core.indicators.helpers.VolumeIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.PreviousValueIndicator', detail: '前值指标', insertText: "import org.ta4j.core.indicators.helpers.PreviousValueIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.DifferenceIndicator', detail: '差值指标', insertText: "import org.ta4j.core.indicators.helpers.DifferenceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.SumIndicator', detail: '求和指标', insertText: "import org.ta4j.core.indicators.helpers.SumIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.CombineIndicator', detail: '组合指标', insertText: "import org.ta4j.core.indicators.helpers.CombineIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.ConstantIndicator', detail: '常量指标', insertText: "import org.ta4j.core.indicators.helpers.ConstantIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.TRIndicator', detail: '真实波幅指标', insertText: "import org.ta4j.core.indicators.helpers.TRIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.TypicalPriceIndicator', detail: '典型价格指标', insertText: "import org.ta4j.core.indicators.helpers.TypicalPriceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.helpers.MedianPriceIndicator', detail: '中间价格指标', insertText: "import org.ta4j.core.indicators.helpers.MedianPriceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.statistics.*', detail: '导入统计指标', insertText: "import org.ta4j.core.indicators.statistics.*;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.statistics.StandardDeviationIndicator', detail: '标准差指标', insertText: "import org.ta4j.core.indicators.statistics.StandardDeviationIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.statistics.VarianceIndicator', detail: '方差指标', insertText: "import org.ta4j.core.indicators.statistics.VarianceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.statistics.CovarianceIndicator', detail: '协方差指标', insertText: "import org.ta4j.core.indicators.statistics.CovarianceIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.statistics.CorrelationCoefficientIndicator', detail: '相关系数指标', insertText: "import org.ta4j.core.indicators.statistics.CorrelationCoefficientIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.statistics.SimpleLinearRegressionIndicator', detail: '线性回归指标', insertText: "import org.ta4j.core.indicators.statistics.SimpleLinearRegressionIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.volume.*', detail: '导入成交量指标', insertText: "import org.ta4j.core.indicators.volume.*;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.volume.OnBalanceVolumeIndicator', detail: '能量潮指标', insertText: "import org.ta4j.core.indicators.volume.OnBalanceVolumeIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.volume.AccumulationDistributionIndicator', detail: '累积分布指标', insertText: "import org.ta4j.core.indicators.volume.AccumulationDistributionIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.volume.ChaikinMoneyFlowIndicator', detail: '蔡金资金流指标', insertText: "import org.ta4j.core.indicators.volume.ChaikinMoneyFlowIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.volume.MoneyFlowIndexIndicator', detail: '资金流量指标', insertText: "import org.ta4j.core.indicators.volume.MoneyFlowIndexIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.volume.NVIIndicator', detail: '负量指标', insertText: "import org.ta4j.core.indicators.volume.NVIIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.indicators.volume.PVIIndicator', detail: '正量指标', insertText: "import org.ta4j.core.indicators.volume.PVIIndicator;", type: 'import' },
  { label: 'import org.ta4j.core.rules.*', detail: '导入所有规则', insertText: "import org.ta4j.core.rules.*;", type: 'import' },
  { label: 'import org.ta4j.core.rules.CrossedUpIndicatorRule', detail: '上穿规则', insertText: "import org.ta4j.core.rules.CrossedUpIndicatorRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.CrossedDownIndicatorRule', detail: '下穿规则', insertText: "import org.ta4j.core.rules.CrossedDownIndicatorRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.OverIndicatorRule', detail: '高于规则', insertText: "import org.ta4j.core.rules.OverIndicatorRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.UnderIndicatorRule', detail: '低于规则', insertText: "import org.ta4j.core.rules.UnderIndicatorRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.StopLossRule', detail: '止损规则', insertText: "import org.ta4j.core.rules.StopLossRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.StopGainRule', detail: '止盈规则', insertText: "import org.ta4j.core.rules.StopGainRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.TrailingStopLossRule', detail: '追踪止损规则', insertText: "import org.ta4j.core.rules.TrailingStopLossRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.AndRule', detail: 'AND规则', insertText: "import org.ta4j.core.rules.AndRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.OrRule', detail: 'OR规则', insertText: "import org.ta4j.core.rules.OrRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.NotRule', detail: 'NOT规则', insertText: "import org.ta4j.core.rules.NotRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.BooleanIndicatorRule', detail: '布尔指标规则', insertText: "import org.ta4j.core.rules.BooleanIndicatorRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.IsRisingRule', detail: '上升规则', insertText: "import org.ta4j.core.rules.IsRisingRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.IsFallingRule', detail: '下降规则', insertText: "import org.ta4j.core.rules.IsFallingRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.IsHighestRule', detail: '最高值规则', insertText: "import org.ta4j.core.rules.IsHighestRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.IsLowestRule', detail: '最低值规则', insertText: "import org.ta4j.core.rules.IsLowestRule;", type: 'import' },
  { label: 'import org.ta4j.core.rules.InPipeRule', detail: '区间规则', insertText: "import org.ta4j.core.rules.InPipeRule;", type: 'import' },
]

const TA4J_CLASSES: Ta4jCompletion[] = [
  { label: 'BarSeries', detail: 'org.ta4j.core.BarSeries - K线数据序列', insertText: 'BarSeries', type: 'class' },
  { label: 'BaseBarSeriesBuilder', detail: 'org.ta4j.core.BaseBarSeriesBuilder - K线序列构建器', insertText: 'BaseBarSeriesBuilder', type: 'class' },
  { label: 'Indicator', detail: 'org.ta4j.core.Indicator<T> - 指标接口', insertText: 'Indicator', type: 'class' },
  { label: 'Rule', detail: 'org.ta4j.core.Rule - 交易规则接口', insertText: 'Rule', type: 'class' },
  { label: 'Strategy', detail: 'org.ta4j.core.Strategy - 交易策略接口', insertText: 'Strategy', type: 'class' },
  { label: 'BaseStrategy', detail: 'org.ta4j.core.BaseStrategy - 策略实现类', insertText: 'BaseStrategy', type: 'class' },
  { label: 'Num', detail: 'org.ta4j.core.num.Num - 数值类型', insertText: 'Num', type: 'class' },
  { label: 'DecimalNumFactory', detail: 'org.ta4j.core.num.DecimalNumFactory - 高精度数值工厂', insertText: 'DecimalNumFactory', type: 'class' },
  { label: 'TradingRecord', detail: 'org.ta4j.core.TradingRecord - 交易记录', insertText: 'TradingRecord', type: 'class' },
  { label: 'Trade', detail: 'org.ta4j.core.Trade - 单笔交易', insertText: 'Trade', type: 'class' },
  { label: 'Position', detail: 'org.ta4j.core.Position - 持仓', insertText: 'Position', type: 'class' },
  { label: 'BarSeriesManager', detail: 'org.ta4j.core.backtest.BarSeriesManager - 序列管理器', insertText: 'BarSeriesManager', type: 'class' },
  { label: 'SMAIndicator', detail: 'org.ta4j.core.indicators.averages.SMAIndicator - 简单移动平均线(Indicator, barCount)', insertText: 'SMAIndicator', type: 'class' },
  { label: 'EMAIndicator', detail: 'org.ta4j.core.indicators.averages.EMAIndicator - 指数移动平均线(Indicator, barCount)', insertText: 'EMAIndicator', type: 'class' },
  { label: 'WMAIndicator', detail: 'org.ta4j.core.indicators.averages.WMAIndicator - 加权移动平均线(Indicator, barCount)', insertText: 'WMAIndicator', type: 'class' },
  { label: 'LWMAIndicator', detail: 'org.ta4j.core.indicators.averages.LWMAIndicator - 线性加权移动平均线(Indicator, barCount)', insertText: 'LWMAIndicator', type: 'class' },
  { label: 'MACDIndicator', detail: 'org.ta4j.core.indicators.MACDIndicator - MACD指标(Indicator, shortBarCount, longBarCount)', insertText: 'MACDIndicator', type: 'class' },
  { label: 'RSIIndicator', detail: 'org.ta4j.core.indicators.RSIIndicator - RSI相对强弱指标(Indicator, barCount)', insertText: 'RSIIndicator', type: 'class' },
  { label: 'ATRIndicator', detail: 'org.ta4j.core.indicators.ATRIndicator - 真实波幅均值(BarSeries, barCount)', insertText: 'ATRIndicator', type: 'class' },
  { label: 'CCIIndicator', detail: 'org.ta4j.core.indicators.CCIIndicator - 商品通道指标(BarSeries, barCount)', insertText: 'CCIIndicator', type: 'class' },
  { label: 'WilliamsRIndicator', detail: 'org.ta4j.core.indicators.WilliamsRIndicator - 威廉指标(BarSeries, barCount)', insertText: 'WilliamsRIndicator', type: 'class' },
  { label: 'ParabolicSarIndicator', detail: 'org.ta4j.core.indicators.ParabolicSarIndicator - 抛物线SAR指标(BarSeries)', insertText: 'ParabolicSarIndicator', type: 'class' },
  { label: 'DPOIndicator', detail: 'org.ta4j.core.indicators.DPOIndicator - 去趋势价格指标(BarSeries, barCount)', insertText: 'DPOIndicator', type: 'class' },
  { label: 'PPOIndicator', detail: 'org.ta4j.core.indicators.PPOIndicator - 价格震荡百分比(Indicator, shortBarCount, longBarCount)', insertText: 'PPOIndicator', type: 'class' },
  { label: 'ROCIndicator', detail: 'org.ta4j.core.indicators.ROCIndicator - 变动率指标(Indicator, barCount)', insertText: 'ROCIndicator', type: 'class' },
  { label: 'ChopIndicator', detail: 'org.ta4j.core.indicators.ChopIndicator - Choppiness指数(BarSeries, timeFrame, scaleUpTo)', insertText: 'ChopIndicator', type: 'class' },
  { label: 'StochasticOscillatorKIndicator', detail: 'org.ta4j.core.indicators.StochasticOscillatorKIndicator - KDJ之K值(BarSeries, barCount)', insertText: 'StochasticOscillatorKIndicator', type: 'class' },
  { label: 'StochasticOscillatorDIndicator', detail: 'org.ta4j.core.indicators.StochasticOscillatorDIndicator - KDJ之D值(KIndicator)', insertText: 'StochasticOscillatorDIndicator', type: 'class' },
  { label: 'IchimokuTenkanSenIndicator', detail: 'org.ta4j.core.indicators.ichimoku.IchimokuTenkanSenIndicator - 一目转换线(BarSeries, barCount)', insertText: 'IchimokuTenkanSenIndicator', type: 'class' },
  { label: 'IchimokuKijunSenIndicator', detail: 'org.ta4j.core.indicators.ichimoku.IchimokuKijunSenIndicator - 一目基准线(BarSeries, barCount)', insertText: 'IchimokuKijunSenIndicator', type: 'class' },
  { label: 'IchimokuSenkouSpanAIndicator', detail: 'org.ta4j.core.indicators.ichimoku.IchimokuSenkouSpanAIndicator - 一目先行带A(BarSeries, barCountTenkan, barCountKijun)', insertText: 'IchimokuSenkouSpanAIndicator', type: 'class' },
  { label: 'IchimokuSenkouSpanBIndicator', detail: 'org.ta4j.core.indicators.ichimoku.IchimokuSenkouSpanBIndicator - 一目先行带B(BarSeries, barCount)', insertText: 'IchimokuSenkouSpanBIndicator', type: 'class' },
  { label: 'IchimokuChikouSpanIndicator', detail: 'org.ta4j.core.indicators.ichimoku.IchimokuChikouSpanIndicator - 一目延迟线(BarSeries, barCount)', insertText: 'IchimokuChikouSpanIndicator', type: 'class' },
  { label: 'BullishEngulfingIndicator', detail: 'org.ta4j.core.indicators.candles.BullishEngulfingIndicator - 看涨吞没形态(BarSeries)', insertText: 'BullishEngulfingIndicator', type: 'class' },
  { label: 'BearishEngulfingIndicator', detail: 'org.ta4j.core.indicators.candles.BearishEngulfingIndicator - 看跌吞没形态(BarSeries)', insertText: 'BearishEngulfingIndicator', type: 'class' },
  { label: 'HammerIndicator', detail: 'org.ta4j.core.indicators.candles.HammerIndicator - 锤子线形态(BarSeries)', insertText: 'HammerIndicator', type: 'class' },
  { label: 'DojiIndicator', detail: 'org.ta4j.core.indicators.candles.DojiIndicator - 十字星形态(BarSeries, barCount, factor)', insertText: 'DojiIndicator', type: 'class' },
  { label: 'MorningStarIndicator', detail: 'org.ta4j.core.indicators.candles.MorningStarIndicator - 晨星形态(BarSeries)', insertText: 'MorningStarIndicator', type: 'class' },
  { label: 'EveningStarIndicator', detail: 'org.ta4j.core.indicators.candles.EveningStarIndicator - 暮星形态(BarSeries)', insertText: 'EveningStarIndicator', type: 'class' },
  { label: 'BollingerBandsLowerIndicator', detail: 'org.ta4j.core.indicators.bollinger.BollingerBandsLowerIndicator - 布林带下轨(BollingerBandsMiddleIndicator)', insertText: 'BollingerBandsLowerIndicator', type: 'class' },
  { label: 'BollingerBandsMiddleIndicator', detail: 'org.ta4j.core.indicators.bollinger.BollingerBandsMiddleIndicator - 布林带中轨(SMAIndicator)', insertText: 'BollingerBandsMiddleIndicator', type: 'class' },
  { label: 'BollingerBandsUpperIndicator', detail: 'org.ta4j.core.indicators.bollinger.BollingerBandsUpperIndicator - 布林带上轨(BollingerBandsMiddleIndicator)', insertText: 'BollingerBandsUpperIndicator', type: 'class' },
  { label: 'ClosePriceIndicator', detail: 'org.ta4j.core.indicators.helpers.ClosePriceIndicator - 收盘价指标(BarSeries)', insertText: 'ClosePriceIndicator', type: 'class' },
  { label: 'OpenPriceIndicator', detail: 'org.ta4j.core.indicators.helpers.OpenPriceIndicator - 开盘价指标(BarSeries)', insertText: 'OpenPriceIndicator', type: 'class' },
  { label: 'HighPriceIndicator', detail: 'org.ta4j.core.indicators.helpers.HighPriceIndicator - 最高价指标(BarSeries)', insertText: 'HighPriceIndicator', type: 'class' },
  { label: 'LowPriceIndicator', detail: 'org.ta4j.core.indicators.helpers.LowPriceIndicator - 最低价指标(BarSeries)', insertText: 'LowPriceIndicator', type: 'class' },
  { label: 'VolumeIndicator', detail: 'org.ta4j.core.indicators.helpers.VolumeIndicator - 成交量指标(BarSeries)', insertText: 'VolumeIndicator', type: 'class' },
  { label: 'PreviousValueIndicator', detail: 'org.ta4j.core.indicators.helpers.PreviousValueIndicator - 前值指标(Indicator, n)', insertText: 'PreviousValueIndicator', type: 'class' },
  { label: 'DifferenceIndicator', detail: 'org.ta4j.core.indicators.helpers.DifferenceIndicator - 差值指标(CombineIndicator.minus)', insertText: 'DifferenceIndicator', type: 'class' },
  { label: 'SumIndicator', detail: 'org.ta4j.core.indicators.helpers.SumIndicator - 求和指标(Indicator, Indicator)', insertText: 'SumIndicator', type: 'class' },
  { label: 'CombineIndicator', detail: 'org.ta4j.core.indicators.helpers.CombineIndicator - 组合指标(plus/minus/multiply/divide)', insertText: 'CombineIndicator', type: 'class' },
  { label: 'ConstantIndicator', detail: 'org.ta4j.core.indicators.helpers.ConstantIndicator<T> - 常量指标(BarSeries, Num)', insertText: 'ConstantIndicator', type: 'class' },
  { label: 'TRIndicator', detail: 'org.ta4j.core.indicators.helpers.TRIndicator - 真实波幅指标(BarSeries)', insertText: 'TRIndicator', type: 'class' },
  { label: 'TypicalPriceIndicator', detail: 'org.ta4j.core.indicators.helpers.TypicalPriceIndicator - 典型价格指标(BarSeries)', insertText: 'TypicalPriceIndicator', type: 'class' },
  { label: 'MedianPriceIndicator', detail: 'org.ta4j.core.indicators.helpers.MedianPriceIndicator - 中间价格指标(BarSeries)', insertText: 'MedianPriceIndicator', type: 'class' },
  { label: 'StandardDeviationIndicator', detail: 'org.ta4j.core.indicators.statistics.StandardDeviationIndicator - 标准差指标(Indicator, barCount)', insertText: 'StandardDeviationIndicator', type: 'class' },
  { label: 'VarianceIndicator', detail: 'org.ta4j.core.indicators.statistics.VarianceIndicator - 方差指标(Indicator, barCount)', insertText: 'VarianceIndicator', type: 'class' },
  { label: 'CovarianceIndicator', detail: 'org.ta4j.core.indicators.statistics.CovarianceIndicator - 协方差指标(Indicator, Indicator, barCount)', insertText: 'CovarianceIndicator', type: 'class' },
  { label: 'CorrelationCoefficientIndicator', detail: 'org.ta4j.core.indicators.statistics.CorrelationCoefficientIndicator - 相关系数指标(Indicator, Indicator, barCount)', insertText: 'CorrelationCoefficientIndicator', type: 'class' },
  { label: 'SimpleLinearRegressionIndicator', detail: 'org.ta4j.core.indicators.statistics.SimpleLinearRegressionIndicator - 线性回归指标(Indicator, barCount)', insertText: 'SimpleLinearRegressionIndicator', type: 'class' },
  { label: 'OnBalanceVolumeIndicator', detail: 'org.ta4j.core.indicators.volume.OnBalanceVolumeIndicator - 能量潮指标(BarSeries)', insertText: 'OnBalanceVolumeIndicator', type: 'class' },
  { label: 'AccumulationDistributionIndicator', detail: 'org.ta4j.core.indicators.volume.AccumulationDistributionIndicator - 累积分布指标(BarSeries)', insertText: 'AccumulationDistributionIndicator', type: 'class' },
  { label: 'ChaikinMoneyFlowIndicator', detail: 'org.ta4j.core.indicators.volume.ChaikinMoneyFlowIndicator - 蔡金资金流指标(BarSeries, barCount)', insertText: 'ChaikinMoneyFlowIndicator', type: 'class' },
  { label: 'MoneyFlowIndexIndicator', detail: 'org.ta4j.core.indicators.volume.MoneyFlowIndexIndicator - 资金流量指标(BarSeries, barCount)', insertText: 'MoneyFlowIndexIndicator', type: 'class' },
  { label: 'NVIIndicator', detail: 'org.ta4j.core.indicators.volume.NVIIndicator - 负量指标(BarSeries)', insertText: 'NVIIndicator', type: 'class' },
  { label: 'PVIIndicator', detail: 'org.ta4j.core.indicators.volume.PVIIndicator - 正量指标(BarSeries)', insertText: 'PVIIndicator', type: 'class' },
  { label: 'CrossedUpIndicatorRule', detail: 'org.ta4j.core.rules.CrossedUpIndicatorRule - 上穿规则(Indicator, Indicator)', insertText: 'CrossedUpIndicatorRule', type: 'class' },
  { label: 'CrossedDownIndicatorRule', detail: 'org.ta4j.core.rules.CrossedDownIndicatorRule - 下穿规则(Indicator, Indicator)', insertText: 'CrossedDownIndicatorRule', type: 'class' },
  { label: 'OverIndicatorRule', detail: 'org.ta4j.core.rules.OverIndicatorRule - 高于规则(Indicator, Indicator)', insertText: 'OverIndicatorRule', type: 'class' },
  { label: 'UnderIndicatorRule', detail: 'org.ta4j.core.rules.UnderIndicatorRule - 低于规则(Indicator, Indicator)', insertText: 'UnderIndicatorRule', type: 'class' },
  { label: 'BooleanIndicatorRule', detail: 'org.ta4j.core.rules.BooleanIndicatorRule - 布尔指标规则(Indicator)', insertText: 'BooleanIndicatorRule', type: 'class' },
  { label: 'AndRule', detail: 'org.ta4j.core.rules.AndRule - AND规则(Rule...)', insertText: 'AndRule', type: 'class' },
  { label: 'OrRule', detail: 'org.ta4j.core.rules.OrRule - OR规则(Rule...)', insertText: 'OrRule', type: 'class' },
  { label: 'NotRule', detail: 'org.ta4j.core.rules.NotRule - NOT规则(Rule)', insertText: 'NotRule', type: 'class' },
  { label: 'StopLossRule', detail: 'org.ta4j.core.rules.StopLossRule - 止损规则(Indicator, Num)', insertText: 'StopLossRule', type: 'class' },
  { label: 'StopGainRule', detail: 'org.ta4j.core.rules.StopGainRule - 止盈规则(Indicator, Num)', insertText: 'StopGainRule', type: 'class' },
  { label: 'TrailingStopLossRule', detail: 'org.ta4j.core.rules.TrailingStopLossRule - 追踪止损规则(Indicator, Num)', insertText: 'TrailingStopLossRule', type: 'class' },
  { label: 'IsRisingRule', detail: 'org.ta4j.core.rules.IsRisingRule - 上升规则(Indicator, barCount)', insertText: 'IsRisingRule', type: 'class' },
  { label: 'IsFallingRule', detail: 'org.ta4j.core.rules.IsFallingRule - 下降规则(Indicator, barCount)', insertText: 'IsFallingRule', type: 'class' },
  { label: 'IsHighestRule', detail: 'org.ta4j.core.rules.IsHighestRule - 最高值规则(Indicator, barCount)', insertText: 'IsHighestRule', type: 'class' },
  { label: 'IsLowestRule', detail: 'org.ta4j.core.rules.IsLowestRule - 最低值规则(Indicator, barCount)', insertText: 'IsLowestRule', type: 'class' },
  { label: 'InPipeRule', detail: 'org.ta4j.core.rules.InPipeRule - 区间规则(Indicator, Num, Num)', insertText: 'InPipeRule', type: 'class' },
]

const TA4J_METHODS: Ta4jCompletion[] = [
  { label: 'getBarCount', detail: 'BarSeries.getBarCount() - 获取K线数量', insertText: 'getBarCount()', type: 'method' },
  { label: 'getBar', detail: 'BarSeries.getBar(int index) - 获取指定索引的K线', insertText: 'getBar(${1:index})', type: 'method' },
  { label: 'getBeginIndex', detail: 'BarSeries.getBeginIndex() - 获取起始索引', insertText: 'getBeginIndex()', type: 'method' },
  { label: 'getEndIndex', detail: 'BarSeries.getEndIndex() - 获取结束索引', insertText: 'getEndIndex()', type: 'method' },
  { label: 'addBar', detail: 'BarSeries.addBar(Bar bar) - 添加K线', insertText: 'addBar(${1:bar})', type: 'method' },
  { label: 'getClosePrice', detail: 'Bar.getClosePrice() - 获取收盘价', insertText: 'getClosePrice()', type: 'method' },
  { label: 'getOpenPrice', detail: 'Bar.getOpenPrice() - 获取开盘价', insertText: 'getOpenPrice()', type: 'method' },
  { label: 'getHighPrice', detail: 'Bar.getHighPrice() - 获取最高价', insertText: 'getHighPrice()', type: 'method' },
  { label: 'getLowPrice', detail: 'Bar.getLowPrice() - 获取最低价', insertText: 'getLowPrice()', type: 'method' },
  { label: 'getVolume', detail: 'Bar.getVolume() - 获取成交量', insertText: 'getVolume()', type: 'method' },
  { label: 'getEndTime', detail: 'Bar.getEndTime() - 获取结束时间', insertText: 'getEndTime()', type: 'method' },
  { label: 'getValue', detail: 'Indicator.getValue(int index) - 获取指标值', insertText: 'getValue(${1:index})', type: 'method' },
  { label: 'isSatisfied', detail: 'Rule.isSatisfied(int index) - 判断规则是否满足', insertText: 'isSatisfied(${1:index})', type: 'method' },
  { label: 'and', detail: 'Rule.and(Rule rule) - AND组合规则', insertText: 'and(${1:rule})', type: 'method' },
  { label: 'or', detail: 'Rule.or(Rule rule) - OR组合规则', insertText: 'or(${1:rule})', type: 'method' },
  { label: 'negation', detail: 'Rule.negation() - 取反规则', insertText: 'negation()', type: 'method' },
  { label: 'getEntryRule', detail: 'Strategy.getEntryRule() - 获取入场规则', insertText: 'getEntryRule()', type: 'method' },
  { label: 'getExitRule', detail: 'Strategy.getExitRule() - 获取出场规则', insertText: 'getExitRule()', type: 'method' },
  { label: 'shouldEnter', detail: 'Strategy.shouldEnter(int index) - 是否应该入场', insertText: 'shouldEnter(${1:index})', type: 'method' },
  { label: 'shouldExit', detail: 'Strategy.shouldExit(int index) - 是否应该出场', insertText: 'shouldExit(${1:index})', type: 'method' },
  { label: 'run', detail: 'BarSeriesManager.run(Strategy) - 运行策略', insertText: 'run(${1:strategy})', type: 'method' },
  { label: 'getPositions', detail: 'TradingRecord.getPositions() - 获取所有持仓', insertText: 'getPositions()', type: 'method' },
  { label: 'getEntry', detail: 'Trade.getEntry() - 获取入场订单', insertText: 'getEntry()', type: 'method' },
  { label: 'getExit', detail: 'Trade.getExit() - 获取出场订单', insertText: 'getExit()', type: 'method' },
  { label: 'isClosed', detail: 'Trade.isClosed() - 是否已平仓', insertText: 'isClosed()', type: 'method' },
  { label: 'getPricePerAsset', detail: 'Order.getPricePerAsset() - 获取订单价格', insertText: 'getPricePerAsset()', type: 'method' },
  { label: 'getIndex', detail: 'Order.getIndex() - 获取订单索引', insertText: 'getIndex()', type: 'method' },
  { label: 'numOf', detail: 'series.numFactory().numOf(double val) - 创建Num数值', insertText: 'series.numFactory().numOf(${1:val})', type: 'method' },
  { label: 'plus', detail: 'Num.plus(Num other) - 加法', insertText: 'plus(${1:other})', type: 'method' },
  { label: 'minus', detail: 'Num.minus(Num other) - 减法', insertText: 'minus(${1:other})', type: 'method' },
  { label: 'multipliedBy', detail: 'Num.multipliedBy(Num other) - 乘法', insertText: 'multipliedBy(${1:other})', type: 'method' },
  { label: 'dividedBy', detail: 'Num.dividedBy(Num other) - 除法', insertText: 'dividedBy(${1:other})', type: 'method' },
  { label: 'isGreaterThan', detail: 'Num.isGreaterThan(Num other) - 大于比较', insertText: 'isGreaterThan(${1:other})', type: 'method' },
  { label: 'isLessThan', detail: 'Num.isLessThan(Num other) - 小于比较', insertText: 'isLessThan(${1:other})', type: 'method' },
  { label: 'doubleValue', detail: 'Num.doubleValue() - 转为double', insertText: 'doubleValue()', type: 'method' },
]

export function getTa4jCompletions(): Ta4jCompletion[] {
  return [...TA4J_IMPORTS, ...TA4J_CLASSES, ...TA4J_METHODS]
}
