server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 24h

spring:
  application:
    name: tradingx-backend

  datasource:
    url: jdbc:h2:file:./data/tradingx;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

tushare:
  api-url: https://api.tushare.pro
  token: e0dbbd8c6800d855f7d12c48b0a13a1131d46438b4e80b01b59dd5b5
  stock-basic-csv: /app/static-data/tushare_stock_basic.csv

ai:
  siliconflow:
    api-key: b8a3e137da074c25a8a5dd54cdbe6e5d.FfJ77oKfq5oVBpgj
    base-url: https://open.bigmodel.cn/api/paas/v4
    model: GLM-4.7-FlashX

management:
  endpoints:
    web:
      exposure:
        include: health,info
